version: "3.3"

services:
  web1:
    image: nginx
    container_name: nginx1
    ports:
      - "8001:80"
    volumes:
      - ./html1/:/usr/share/nginx/html
  web2:
    image: nginx
    container_name: nginx2
    ports:
      - "8002:80"
    volumes:
      - ./html2/:/usr/share/nginx/html
  web3:
    image: nginx
    container_name: nginx3
    ports:
      - "8003:80"
    volumes:
      - ./html3/:/usr/share/nginx/html
  lb:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
      - web3
  
volumes:
  html1:
  html2:
  html3: